
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <CUnit/Basic.h>

#include "cryptoal_hash.h"

#include "cryptoal_hash_tests.h"

/* */
void cryptoal_test_hash_sha256(void)
{
    bool res = false;
    unsigned char hash[32+1];
    size_t size = 0u;
    int ii = 0;
    
    FILE * fp;
    unsigned char buffer[32*1024];

    if( ( fp = fopen( "./tests/cryptoal_signature_tests/buffer.txt", "rb" ) ) == NULL )
        CU_ASSERT_EQUAL(1, 0 );
    size = fread( buffer, 1, sizeof(buffer), fp );
    CU_ASSERT_EQUAL( size, 671 );

    res = cryptoal_SHA256( (void *) buffer, size, hash);
    CU_ASSERT_EQUAL( res, true );
  
    printf ("\nHash:  \n");
    for (ii=0; ii<32+1; ii++)
        printf ( "%02x ", hash[ii] );
    printf ("\n\n");




    /* Compare with beginning of  signature generated by openssl manualy in a shell: */
    CU_ASSERT_EQUAL(hash[0], 0xef);
    CU_ASSERT_EQUAL(hash[1], 0x18);
    CU_ASSERT_EQUAL(hash[2], 0x24);
    CU_ASSERT_EQUAL(hash[3], 0x39);
    CU_ASSERT_EQUAL(hash[4], 0xe8);
    CU_ASSERT_EQUAL(hash[5], 0x66);
    CU_ASSERT_EQUAL(hash[6], 0x5c);
    CU_ASSERT_EQUAL(hash[7], 0x20);
    CU_ASSERT_EQUAL(hash[8], 0xd3);
    CU_ASSERT_EQUAL(hash[9], 0xae);
    CU_ASSERT_EQUAL(hash[10], 0x07);
    CU_ASSERT_EQUAL(hash[11], 0x0d);
    CU_ASSERT_EQUAL(hash[12], 0x5e);
    CU_ASSERT_EQUAL(hash[13], 0x12);
    CU_ASSERT_EQUAL(hash[14], 0xad);
    CU_ASSERT_EQUAL(hash[15], 0x84);

    return;
}



/*************** Bouchons for tests ****************/
char theRootPathOfResources[] = "/tmp/";
char * entmgt_launcher_getAppRootPath ()
{
    return theRootPathOfResources;
}


