
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <CUnit/Basic.h>

#include "nal_mem.h"

#include "com_error.h"
#include "cryptoal_signature.h"

#include "cryptoal_signature_tests.h"


/* */
void cryptoal_test_signing_and_verifying_buffer(void)
{
    int returnCode = CRYPTOAL_SUCCESS;
    int ii = 0;
    size_t size = 0u;
    
    FILE * fp;
    unsigned char buffer[32*1024];
    
    if( ( fp = fopen( "./tests/cryptoal_signature_tests/buffer.txt", "rb" ) ) == NULL )
        CU_ASSERT_EQUAL(1, 0 );
    size = fread( buffer, 1, sizeof(buffer), fp );
    CU_ASSERT_EQUAL( size, 671 );
    
    /* Calculate signature */
    int ret = 0 /*MBEDTLS_EXIT_SUCCESS*/ ;
    unsigned char * pSignature = NULL;
    size_t lenSig = 0u;
    bool signatureValid = false;

    ret = cryptoal_hash_signature( (void *) buffer, size, & pSignature, & lenSig);
    printf ("Len of signature = %u\n", lenSig);
    for (ii=0; ii<lenSig; ii++)
        printf ( "%02x ", pSignature[ii] );
    printf ("\n");

    CU_ASSERT_EQUAL(ret, /*MBEDTLS_EXIT_SUCCESS*/ 0 );
    CU_ASSERT_EQUAL((pSignature==0), false);
    CU_ASSERT_EQUAL(lenSig, 256);

    /* Compare with beginning of  signature generated by openssl manualy in a shell: */
    CU_ASSERT_EQUAL(pSignature[0], 0xaf);
    CU_ASSERT_EQUAL(pSignature[1], 0xb7);
    CU_ASSERT_EQUAL(pSignature[2], 0x8f);
    CU_ASSERT_EQUAL(pSignature[3], 0x67);
    CU_ASSERT_EQUAL(pSignature[4], 0xc6);
    CU_ASSERT_EQUAL(pSignature[5], 0x34);
    CU_ASSERT_EQUAL(pSignature[6], 0x68);
    CU_ASSERT_EQUAL(pSignature[7], 0xd3);

    /* Verify a GOOD signature */
    ret = cryptoal_verify_hash_signature( (void *) buffer, size,  false, pSignature, lenSig, & signatureValid);
    
    CU_ASSERT_EQUAL(ret, /*MBEDTLS_EXIT_SUCCESS*/ 0 );
    CU_ASSERT_EQUAL(signatureValid, true);
    
   /* Verify a BAD signature */
    pSignature[34] ++;
    ret = cryptoal_verify_hash_signature( (void *) buffer, size, false, pSignature, lenSig, & signatureValid);
    
    CU_ASSERT_EQUAL(ret, /*MBEDTLS_EXIT_SUCCESS*/ 0 );
    CU_ASSERT_EQUAL(signatureValid, false);

  /* Verify a GOOD signature */
    pSignature[34] --;
    ret = cryptoal_verify_hash_signature( (void *) buffer, size, false, pSignature, lenSig, & signatureValid);
    
    CU_ASSERT_EQUAL(ret, /*MBEDTLS_EXIT_SUCCESS*/ 0 );
    CU_ASSERT_EQUAL(signatureValid, true);

  /* Verify a GOOD signature with bad certificate */
    ret = cryptoal_verify_hash_signature( (void *) buffer, size, true, pSignature, lenSig, & signatureValid);
    
    CU_ASSERT_EQUAL(ret, /*MBEDTLS_EXIT_SUCCESS*/ 0 );
    CU_ASSERT_EQUAL(signatureValid, false);

}


/*************** Bouchons for tests ****************/
char theRootPathOfResources[] = "./tests/cryptoal_signature_tests/";

char * entmgt_launcher_getAppRootPath()
{
    return theRootPathOfResources;
}

